source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XLEasyImageSelect_Example', :exclusive => true do
  pod 'XLEasyImageSelect', :path => '../'
end

target 'XLEasyImageSelect_Tests', :exclusive => true do
  pod 'XLEasyImageSelect', :path => '../'

  
end
