source 'https://github.com/CocoaPods/Specs.git'

target 'XLEasyImageSelect_Example', :exclusive => true do
  pod 'XLEasyImageSelect', :path => '../'
end

target 'XLEasyImageSelect_Tests', :exclusive => true do
  pod 'XLEasyImageSelect', :path => '../'

  
end
